PRAGMA foreign_keys = ON;
CREATE TABLE Persona(
RFC VARCHAR(20) PRIMARY KEY,
Nombre VARCHAR(20) NOT NULL,
Apellido_P VARCHAR(20) NOT NULL,
Apellido_M VARCHAR(20) NOT NULL,
Fecha_Nacimiento DATE NOT NULL,
Sexo char(1) CHECK(Sexo='M' or Sexo='F'),
Ciudad VARCHAR(20) NOT NULL,
Colonia VARCHAR(20) NOT NULL,
Calle VARCHAR(20) NOT NULL,
Numero VARCHAR(20) NOT NULL,
Codigo_postal VARCHAR(20) NOT NULL
);
CREATE TABLE Telefonos_Persona(
RFC VARCHAR(20),
Telefono VARCHAR(20)NOT NULL,
FOREIGN KEY(RFC) REFERENCES Persona(RFC)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE Email_Persona(
RFC VARCHAR(20),
Email VARCHAR(30) NOT NULL,
FOREIGN KEY(RFC) REFERENCES Persona(RFC)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE Cliente(
RFC VARCHAR(20)PRIMARY KEY,
FOREIGN KEY(RFC) REFERENCES Persona(RFC)
ON DELETE NO ACTION
ON UPDATE CASCADE
);
CREATE TABLE Empleado(
RFC VARCHAR(20)PRIMARY KEY,
Sueldo INTEGER NOT NULL CHECK(Sueldo>0),
Turno VARCHAR(20) NOT NULL CHECK(Turno='Matutino' or Turno='Nocturno' or Turno='Diurno'),
FOREIGN KEY(RFC) REFERENCES Persona(RFC)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE Vendedor(
RFC VARCHAR(20)PRIMARY KEY,
FOREIGN KEY(RFC) REFERENCES Empleado(RFC)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE Trabajador_Interno(
RFC VARCHAR(20)PRIMARY KEY,
FOREIGN KEY(RFC) REFERENCES Empleado(RFC)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE Empresa(
RFC VARCHAR(20) PRIMARY KEY,
Nombre VARCHAR(20) NOT NULL,
Ciudad VARCHAR(20) NOT NULL,
Colonia VARCHAR(20) NOT NULL,
Calle  VARCHAR(20) NOT NULL,
Numero VARCHAR(20) NOT NULL,
Codigo_postal VARCHAR(20) NOT NULL,
url_imagen VARCHAR(100)
);
CREATE TABLE Telefonos_Empresa(
RFC VARCHAR(20),
Telefono VARCHAR(20) NOT NULL,
FOREIGN KEY(RFC) REFERENCES Empresa(RFC)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE Email_Empresa(
RFC VARCHAR(20),
Email VARCHAR(30) NOT NULL,
FOREIGN KEY(RFC) REFERENCES Empresa(RFC)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE Celular(
IMEI VARCHAR(20) PRIMARY KEY,
Marca VARCHAR(20) NOT NULL,
Modelo VARCHAR(20) NOT NULL,
Descripcion TEXT NOT NULL
);

CREATE TABLE Servicio(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Descripcion TEXT NOT NULL
);
CREATE TABLE Trabajar(
RFC_Empresa VARCHAR(20),
RFC_Empleado VARCHAR(20),
Fecha_contratacion DATE NOT NULL,
FOREIGN KEY(RFC_Empresa) REFERENCES Empresa(RFC)
ON DELETE CASCADE
ON UPDATE CASCADE,
FOREIGN KEY(RFC_Empleado) REFERENCES Empleado(RFC)
ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE Vender(
IMEI VARCHAR(20),
RFC_Vendedor VARCHAR(20),
Comision FLOAT CHECK (Comision>0 and Comision <1),
FOREIGN KEY(IMEI) REFERENCES Celular(IMEI)
ON DELETE NO ACTION
ON UPDATE CASCADE,
FOREIGN KEY(RFC_Vendedor) REFERENCES Vendedor(RFC)
ON DELETE NO ACTION
ON UPDATE CASCADE
);
CREATE TABLE Comprar(
IMEI VARCHAR(20),
RFC VARCHAR(20),
Id_Servicio VARCHAR(20),
Fecha_Compra DATE NOT NULL,
Pago NUMERIC CHECK(Pago>0),
FOREIGN KEY(IMEI) REFERENCES Celular(IMEI)
ON DELETE NO ACTION
ON UPDATE CASCADE,
FOREIGN KEY(RFC) REFERENCES Cliente(RFC)
ON DELETE NO ACTION
ON UPDATE CASCADE,
FOREIGN KEY(Id_servicio) REFERENCES Servicio(Id)
ON DELETE NO ACTION
ON UPDATE CASCADE
);
CREATE TABLE Pruebas(
Id INTEGER PRIMARY KEY AUTOINCREMENT,
Descripcion text
);	
CREATE TABLE Historial(
Consulta_hecha text
);